sudo: required

language: node_js

node_js:
  - "4.4.3"

services:
  - docker

before_install:
- npm install
- node_modules/selenium-standalone/bin/selenium-standalone install
- docker build -t=coach-plataform:0.0.1 .
- docker run -dt -p 80:9999 coach-plataform:0.0.1

script:
- node node_modules/nightwatch/bin/runner.js -e phantomJS