language: node_js

node_js:
  - "4.2.*"

cache:
  directories:
    - node_modules
    - elm-stuff

before_install:
  - "npm install -g  npm@^4"

install:
  - npm install
  - elm-package install

script:
  - npm run dev