sudo: required

services:
  - docker

env:  
    global:
        - DOCKER_VERSION=1.11.0
        - DOCKER_COMPOSE_VERSION=1.7.0

before_install:
- docker-compose build
- docker-compose up -d

script:
- cd e2e
- WEB_SERVICE='http://127.0.0.1' npm run test
