language: node_js

node_js:
  - "4.2.*"

cache:
  directories:
    - node_modules
    - elm-stuff

before_install:

install:
  - npm install
  - npm install elm -g
  - elm-package install -y
  - node_modules/selenium-standalone/bin/selenium-standalone install

script:
  - npm run api &
  - npm run dev &
  - node node_modules/nightwatch/bin/runner.js